#!/bin/bash

##  This code portion will only disable and remove the FirewallD in Centos 7 
##  Lets Face it FirewallD is horrid an everyone else likes using iptables anyways.. You can skip this step if you realy want to


##  Disable and Stop the FirewallD service before anything else. 
systemctl mask firewalld  #Disable 
systemctl stop firewalld  #Stop 
 
##  Install the iptables related  packages
yum -y install iptables-services 
#I sware that everytime I see Yum It makes me think of cookie monster... Nommm Nooo 

## Install iptables 
systemctl enable iptables #make sure iptables start on load 
systemctl start iptables #start iptables 

## Flush the iptables with toilet duck 
# If you dont get the refearnce go to http://www.scjohnson.com.au/products/duck/ #trentneedssleep
iptables -F
iptables -L

##  Open Port 80 for HTML, 443 for SSL, 25 for SMTP and 465 for secure SMTP, as well as blocking some naught naught ports 

# These are blocking ports - The super nasty Stuff #
iptables -A INPUT -p tcp --tcp-flags ALL NONE -j DROP  #Block null packets 
iptables -A INPUT -p tcp ! --syn -m state --state NEW -j DROP #Block syc-flood attack ports 
iptables -A INPUT -p tcp --tcp-flags ALL ALL -j DROP #XMAS Packets 

# Allowing Ports In #
iptables -A INPUT -i lo -j ACCEPT #Alowing Local Host.. Not normaly needed but just incase 
iptables -A INPUT -p tcp -m tcp --dport 80 -j ACCEPT #HTML 
iptables -A INPUT -p tcp -m tcp --dport 443 -j ACCEPT #SSL 
iptables -A INPUT -p tcp -m tcp --dport 25 -j ACCEPT #SMTP 
iptables -A INPUT -p tcp -m tcp --dport 465 -j ACCEPT #SMTP Secure 
iptables -A INPUT -p tcp -m tcp --dport 110 -j ACCEPT #Email Ports #I still want to know why your not using our email client my.timeformonkeys.com.au for more infomation 
iptables -A INPUT -p tcp -m tcp --dport 995 -j ACCEPT #more email ports
iptables -A INPUT -p tcp -m tcp --dport 143 -j ACCEPT #POP3 Ports (Unsecure) 
iptables -A INPUT -p tcp -m tcp --dport 993 -j ACCEPT #POP3 Ports (Secure)
iptables -A INPUT -p tcp -m tcp --dport 22 -j ACCEPT #SSH Access in 
iptables -A INPUT -p tcp -m tcp --dport 10000 -j ACCEPT #Webmin (More on this later) 
iptables -A INPUT -p tcp -m tcp --dport 5282 -j ACCEPT #Postgres 

#  Block everything else from sniffing around - Lets wrap your server in cotton wool# 
iptables -P OUTPUT ACCEPT #Allow all outgoing transmitions... Lets face it if somone is in your server they can open the ports #stupid
iptables -P INPUT DROP #Ban any other port from coming into the server 

# Save, restart and Show the user again the iptables just for shits and giggles 
iptables-save #Save the Tables 
service iptables restart #restart the tables 
sudo tee /etc/sysconfig/iptables #lets look at the tables 

